default:
  image: node:17.2.0
  before_script:
    - yarn install
    - cd client
    - yarn install
    - cd ../server
    - yarn install
    - cd ..

stages:
  - test
  - build

lint-frontend:
  stage: test
  script:
    - echo "Linting frontend..."
    - cd client
    - yarn lint
    - cd ..
    - echo "Done!"

lint-backend:
  stage: test
  script:
    - echo "Linting backend..."
    - cd server
    - yarn lint
    - cd ..
    - echo "Done!"
  needs: ["lint-frontend"]

build-frontend:
  stage: build
  script:
    - echo "Building frontend..."
    - cd client
    - yarn build
    - apt update
    - apt -y install zip unzip
    - zip -r frontend-build-$CI_PIPELINE_ID.zip .next
    - cd ..
    - echo "Done!"
#  artifacts:
#    paths:
#      - client/frontend-build-*.zip
  needs: ["lint-backend"]

build-backend:
  stage: build
  script:
    - echo "Building backend..."
    - cd server
    - mkdir dist
    - yarn build
    - apt update
    - apt -y install zip unzip
    - zip -r backend-build-$CI_PIPELINE_ID.zip dist
    - rm -rf dist
    - cd ..
    - echo "Done!"
#  artifacts:
#    paths:
#      - server/backend-build-*.zip
  needs: ["build-frontend"]